name: CMake Build TPX3
on: [push]
# jobs:
#   build-windows:
#     runs-on: windows-latest
#     steps:
#       - uses: action/checkout@v3
jobs:
  build-linux:
  runs-on: ubuntu-latest
  working_directory: cheetah/
  steps:
    - uses: action/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y build-essential cmake
    - run: mkdir build && cd build && cmake .. && make
    - uses: action/upload-artifact@v3
      with: 
        name: TPX3.out
        path: build/


