name: CMake Build TPX3
on: [push]
# jobs:
#   build-windows:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v3
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y build-essential cmake
      - name: build
        working-directory: cheetah/
        run: mkdir build && cd build && cmake .. && make
      - uses: actions/upload-artifact@v3
        with: 
          name: TPX3.out
          path: cheetah/build/


